#!/usr/bin/python

import Adafruit_BMP.BMP085 as BMP085 #  BMP library

sensor = BMP085.BMP085()
print 'Temp = {0:0.2f} *C'.format(sensor.read_temperature()) # Temperature 
print 'Pressure = {0:0.2f} Pa'.format(sensor.read_pressure()) # pressure
print 'Altitude = {0:0.2f} m'.format(sensor.read_altitude()) #  altitude
